### ISSUE TITLE
Wrong glottocode wee1234

### ISSUE THREAD

**Issue by xrotwang** [bambooforest/phoible-scripts#5]
The glottocode `wee1234` assinged to Minjungbal is invalid; should be [`twee1234`](https://glottolog.org/resource/languoid/id/twee1234).

**Comment by bambooforest** [comment]
@bambooforest write test

**Comment by bambooforest** [comment]
fixed in https://github.com/phoible/dev/pull/207 

@xrotwang the phoible index still has 2 inventories with NA for Glottocodes, but it doesn't seem like these will be resolved soon. i've left them in the CLDF dump, FYI.

https://github.com/bambooforest/phoible-scripts/blob/master/tests/tests.md
