### ISSUE TITLE
Which references.bib should I use?

### ISSUE THREAD

**Issue by xrotwang** [bambooforest/phoible-scripts#6]
[phoible-references.bib](https://github.com/phoible/dev/blob/master/data/phoible-references.bib) doesn't seem to fully match the citation keys in `values.csv`.

This BibTeX file also contains characters in citation keys which I'd like to avoid: `:` and `/`.

**Comment by bambooforest** [comment]
@xrotwang - quick clarification, are we missing references or are there too many? phoible-refs has legacy refs, so there isn't clear one-to-one mapping from refs to index/values

**Comment by bambooforest** [comment]
I'll go ahead and write a test for this and some other things on the list (#5 )

**Comment by bambooforest** [comment]
Looks like we were missing some references in phoible 2014, e.g.

https://phoible.org/inventories/view/201

but the majority of these are from RA (all 100 data points are missing): 

https://github.com/bambooforest/phoible-scripts/blob/master/tests/tests.md

I'll figure out what's going on here and update the references file.

**Comment by bambooforest** [comment]
@xrotwang - [phoible-references.bib](https://github.com/phoible/dev/blob/master/data/phoible-references.bib) should now match all values after:

https://github.com/phoible/dev/pull/206

if you find anything strange, let me know.
